import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")
print("Testuję klucz API:", openai.api_key[:8], "...")

try:
    response = openai.ChatCompletion.create(
        model="gpt-4-turbo",
        messages=[{"role": "user", "content": "Test API"}],
        max_tokens=10
    )
    print("Odpowiedź z OpenAI:", response.choices[0].message["content"])
except Exception as e:
    print("Błąd połączenia z OpenAI:", e)


name: Auto Summarize Documents (PDF, DOCX, ODT, OCR)

on:
  push:
    paths:
      - 'Cywilna/**'
      - 'Apelacja/**'
      - 'Egzekucja/**'

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          pip install pdfplumber python-docx openai pytesseract Pillow odfpy

      - name: Generate summaries
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/auto_summary.py

      - name: Commit summaries
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Cywilna/knowledge.md Apelacja/knowledge.md Egzekucja/knowledge.md
          git commit -m "Auto summary update (PDF, DOCX, ODT, OCR)" || echo "No changes"
          git push || echo "Nothing to push"
