name: Auto-update knowledge.md

on:
  push:
    paths:
      - 'Cywilna/**'
      - 'Apelacja/**'
      - 'Egzekucja/**'

jobs:
  update-knowledge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-frontmatter

      - name: Update knowledge.md
        run: python .github/scripts/update_knowledge.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Cywilna/knowledge.md Apelacja/knowledge.md Egzekucja/knowledge.md
          git commit -m "Automatyczna aktualizacja knowledge.md" || echo "Brak zmian"
          git push || echo "Brak zmian do wypchnięcia"
